version: "3.3"
services:
 liquibase:
  image:  liquibase-docker
  network_mode: "host"
  depends_on: 
   - mysql_db
   - postgres_db
  volumes:
    - type: bind
      source: ./resources/liquibase/db
      target: /liquibase/db
  environment:
     # supports (mysql / postgresql)
     DB_TYPE: mysql
     DB_USERNAME: datamanagement
     DB_PASSWORD: d9bb49a8aa33e60e34faa71055
     DB_URL: jdbc:mysql://localhost:3306/datamanagement

 mysql_db:
  image: mysql:latest
  network_mode: "host"
  ports:
   - 3306:3306
  environment:
   MYSQL_ROOT_PASSWORD: MYSQL_RANDOM_ROOT_PASSWORD
   MYSQL_DATABASE: datamanagement
   MYSQL_USER: datamanagement
   MYSQL_PASSWORD: d9bb49a8aa33e60e34faa71055

 postgres_db:
  image: postgres:latest
  network_mode: "host"
  ports:
   - 5432:5432
  environment:
   POSTGRES_DB: datamanagement
   POSTGRES_USER: datamanagement
   POSTGRES_PASSWORD: d9bb49a8aa33e60e34faa71055


